# Tenser Flow
> Using Programs with Data is focused on SQL and database actions.  Part A focuses on SQLAlchemy and an OOP programming style.

- toc: true 
- badges: true
- comments: true
- categories: [jupyter, week-28]

## What is Pandas?

Pandas is an open source Python package which is used for data analysis and machine learning. Pandas is built using numpy which supports it using multidimensional arrays such as what is shown below:

In [6]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])

print(a)

b = np.reshape(
               a,     # the array to be reshaped
               (2,3)  # dimensions of the new array
              )

print(b) 

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Data can then be manipulated using pandas to do all sorts of different things such as data cleaning, statistical analysis, and data visualization. Below is an example of data visualization in a table using pandas.

In [1]:
import pandas as pd

pd.__version__

'1.4.2'

In [2]:
classes = pd.Series(["Mathematics","Chemistry","Physics","History","Geography","German"])

grades  = pd.Series([90,54,77,22,25])


pd.DataFrame({"Classes": classes, "Grades": grades})

Classes  Grades
0  Mathematics    90.0
1    Chemistry    54.0
2      Physics    77.0
3      History    22.0
4    Geography    25.0
5       German     NaN

## What is TenserFlow?

Tensor Flow is a machine learning platform which has tools to validate and transform large datasets and also provides standard datasets for machine learning training.

An example of this is the fashion MNIST (Modified National Institute of Standards and Technology) database:

In this dataset there are many pictures which are each28x28 Numpy arrays.